export const MESSAGES = {
  DATA_FETCH_SUCCESS: "Data fetched successfully.",
  LOGIN_SUCCESS: "Login successful.",
  DATA_SAVED: "Data saved successfully.",
  USER_NOT_FOUND: "User not found.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  INTERNAL_SERVER_ERROR: "Internal server error.",
  LOGIN_INVALID: "Invalid user ID or password.",
  OTP_SENT_SUCCESS: "OTP sent successfully",
  EMAIL_VERIFIED_SUCCESS: "Email Verified successfully",
  REQUIRED_FIELDS: "Please fill all required fields.",
  RESET_LINK_SENT: "A password reset link has been sent to your registered email successfully.",
  EMAIL_VERIFICATION_OTP_SENT: "A Email verification otp  has been sent to your registered email successfully.",
  RESET_LINK_ERROR: "An error occurred while sending the password reset link.",
  PASSWORD_UPDATED: "Password updated successfully.",
  TOKEN_EXPIRED: "The link has been expired, please request a new one",
  TOKEN_NOT_FOUND: "The link has been expired, please request a new one",
  OTP_EXPIRED: "The OTP has expired, please request a new one.",
  OTP_NOT_FOUND: "OTP not found or has already been used.",
  INVALID_OTP: "Invalid OTP, please try again.",
  MOBILE_VERIFICATION_OTP_SENT: "Mobile verification OTP has been sent.",
  MOBILE_VERIFIED_SUCCESS: "Mobile number verified successfully.",
  TOKEN_FOUND: "Token  found",
  TOKEN_FOUND_VALID: "Token is Valid",
  INVALID_TOKEN: "The link has been expired, please request a new one",
  RESET_ERROR: "An error occurred while processing your password reset request.",
  CONTACT_SAVED: "Message sent successfully. We’ll get back to you shortly.",
  CONTACT_NOT_FOUND: "No contact messages found.",
  CONTACT_DELETED: "Contact deleted successfully.",
  NO_FILE_UPLOAD: "No file uploaded",
  PROFILE_UPDATED: "Profile updated successfully.",
  ACCESS_DENIED: "Access Denied. No token provided.",
  VIN_NOT_FOUND: "We are not monitoring the entered VIN. Do you want to run a new VIN report?",
  NOT_UPDATED: "Changes were not made.",
  TEST_MSG: "hi",
  MOBILE_REQUIRED: "Mobile number is required.",
  INVALID_USER_TYPE: "User type must be recruiter or seeker.",
  USER_REGISTERED: "User registered successfully, OTP sent.",
  OTP_SENT: "OTP sent successfully.",
  TOKEN_VALID: "Token is valid.",
  TOKEN_INVALID: "Invalid or expired token.",
  CATEGORY_CREATED: "Category created successfully",
  CATEGORY_FETCHED: "Category fetched successfully",
  CATEGORIES_FETCHED: "All categories fetched successfully",
  CATEGORY_UPDATED: "Category updated successfully",
  CATEGORY_DELETED: "Category deleted successfully",
  ALREADY_EXISTS: (field: string = "data") => `${field} already exists.`,
  CATEGORY_NOT_FOUND: "Category not found",
  COUNTRY_CREATED: "Country created successfully",
  COUNTRIES_FETCHED: "Countries fetched successfully",
  COUNTRY_FETCHED: "Country fetched successfully",
  COUNTRY_UPDATED: "Country updated successfully",
  COUNTRY_DELETED: "Country deleted successfully",
  COUNTRY_NOT_FOUND: "Country not found",
  COUNTRY_ALREADY_EXISTS: "Country with same name or code already exists",
  STATE_CREATED: "State created successfully",
  STATES_FETCHED: "States fetched successfully",
  STATE_FETCHED: "State fetched successfully",
  STATE_UPDATED: "State updated successfully",
  STATE_DELETED: "State deleted successfully",
  STATE_NOT_FOUND: "State not found",
  STATE_ALREADY_EXISTS: "State with same name or code already exists",
  CITY_CREATED: "City created successfully.",
  CITY_FETCHED: "City fetched successfully.",
  CITIES_FETCHED: "Cities fetched successfully.",
  CITY_UPDATED: "City updated successfully.",
  CITY_DELETED: "City deleted successfully.",
  CITY_NOT_FOUND: "City not found.",
  CITY_ALREADY_EXISTS: "City with same name or code already exists.",
  LOCALITY_CREATED: "Locality created successfully",
  LOCALITY_UPDATED: "Locality updated successfully",
  LOCALITY_DELETED: "Locality deleted successfully",
  LOCALITY_NOT_FOUND: "Locality not found",
  LOCALITIES_FETCHED: "Localities fetched successfully",
  QUESTION_CREATED: "Question created successfully.",
  QUESTIONS_FETCHED: "Questions fetched successfully.",
  QUESTION_NOT_FOUND: "Question not found.",
  QUESTION_UPDATED: "Question updated successfully.",
  QUESTION_DELETED: "Question deleted successfully.",
  OPTION_CREATED: "Question option created successfully.",
  OPTIONS_FETCHED: "Question options fetched successfully.",
  OPTION_UPDATED: "Question option updated successfully.",
  OPTION_DELETED: "Question option deleted successfully.",
  OPTION_NOT_FOUND: "Question option not found.",

  ANSWER_CREATED: "Answer created successfully.",
  ANSWERS_FETCHED: "Answers fetched successfully.",
  ANSWER_UPDATED: "Answer updated successfully.",
  ANSWER_DELETED: "Answer deleted successfully.",
  ANSWER_NOT_FOUND: "Answer not found.",

  RECRUITER_DOCUMENT_CREATED: "Recruiter document created successfully.",
  RECRUITER_DOCUMENT_FETCHED: "Recruiter documents fetched successfully.",
  RECRUITER_DOCUMENT_UPDATED: "Recruiter document updated successfully.",
  RECRUITER_DOCUMENT_DELETED: "Recruiter document deleted successfully.",
  RECRUITER_DOCUMENT_NOT_FOUND: "Recruiter document not found.",

  DOCUMENT_CREATED: "Recruiter document created successfully",
  DOCUMENT_FETCHED: "Recruiter documents fetched successfully",
  DOCUMENT_UPDATED: "Recruiter document updated successfully",
  DOCUMENT_DELETED: "Recruiter document deleted successfully",
  DOCUMENT_NOT_FOUND: "Recruiter document not found",
  DOCUMENT_ALREADY_EXISTS: "Recruiter document already exists",
  MASTER_SKILL_CREATED: "Master skill created successfully.",
  MASTER_SKILL_FETCHED: "Master skills fetched successfully.",
  MASTER_SKILL_UPDATED: "Master skill updated successfully.",
  MASTER_SKILL_DELETED: "Master skill deleted successfully.",
  MASTER_SKILL_NOT_FOUND: "Master skill not found.",
  JOB_BENEFIT_CREATED: "Job benefit created successfully",
  JOB_BENEFIT_FETCHED: "Job benefits fetched successfully",
  JOB_BENEFIT_UPDATED: "Job benefit updated successfully",
  JOB_BENEFIT_DELETED: "Job benefit deleted successfully",
  JOB_BENEFIT_NOT_FOUND: "Job benefit not found",

};
